### 일반 사용자 회원가입 (아이디 중복 X, 아이디 길이 제한은 6이상 20이하이다.) (패스워드 길이제한은 8이상 20이하이다.) (닉네임 중복 X, 길이 제한은 2이상 12이하이다.)
POST http://localhost:8085/auth/signup_user
Content-Type: application/json

{
  "signupid": "user001",
  "password": "abcd001!?",
  "nickname": "안녕하세요"
}

### 관리자 회원가입 (아이디 중복 X, 아이디 길이 제한은 6이상 20이하이다.) (패스워드 길이제한은 8이상 20이하이다.) (닉네임 중복 X, 길이 제한은 2이상 12이하이다.)
POST http://localhost:8085/auth/signup_admin
Content-Type: application/json

{
  "signupid": "admin001",
  "password": "admin0101",
  "nickname": "ADMINADMIN"
}

### 로그인 (아이디 길이 제한은 6이상 20이하이다.) (패스워드 길이제한은 8이상 20이하이다.)
POST http://localhost:8085/auth/signin
Content-Type: application/json

{
  "signupid": "admin001",
  "password": "admin0101"
}

### 현재 로그인중인 사용자 정보 가져오기 (비밀번호 같은 민감한 정보는 반환되지 않습니다.)
GET http://localhost:8085/auth/signin_information
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDAxIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxOTkxMTMxNiwiZXhwIjoxNzE5OTE0OTE2fQ.k5M4sirFTNQVsS0yrTE3Av6F_xMxyz_SB09YAPvVDFvWp1KdhnH9AKshH9hDEWGnQtV6A07H77oOj3QxaBuBbA

### 사용자 고유 번호를 기반으로 다른 사용자 정보 가져오기 (로그인 필요 x)
GET http://localhost:8085/auth/information?id=18


### 비밀번호 또는 닉네임 변경 (패스워드 길이제한은 8이상 20이하이다.)  (닉네임 중복 X, 길이 제한은 2이상 12이하이다.)
PUT http://localhost:8085/auth/update
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDAxIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxOTkxMTMxNiwiZXhwIjoxNzE5OTE0OTE2fQ.k5M4sirFTNQVsS0yrTE3Av6F_xMxyz_SB09YAPvVDFvWp1KdhnH9AKshH9hDEWGnQtV6A07H77oOj3QxaBuBbA
Content-Type: application/json

{
  "password": "abcd001!?",
  "nickname": "김치사발면"
}


### 유저 계정 잠금 (아이디 길이 제한은 6이상 20이하이다.) (관리자 계정으로 유저 계정을 잠그는 것만 가능)
PUT http://localhost:8085/auth/lock
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxcXFxcXFxcSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzE5NDExNTIxLCJleHAiOjE3MTk0MTUxMjF9.GL3jBIWhkz6fHk5KDjq2HTLsAZ35iMzYJCg9JGzHpXHDHFpnjFCUfO9pe57zwrxQmZWv4jnMRu2VWzJodsz4Bw
Content-Type: application/json

{
  "signupid": "uuuu9999"
}

### 유저 계정 잠금 해제 (아이디 길이 제한은 6이상 20이하이다.) (관리자 계정으로 유저 계정을 잠금 해제하는 것만 가능)
PUT http://localhost:8085/auth/unlock
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxcXFxcXFxcSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzE5NDExNTIxLCJleHAiOjE3MTk0MTUxMjF9.GL3jBIWhkz6fHk5KDjq2HTLsAZ35iMzYJCg9JGzHpXHDHFpnjFCUfO9pe57zwrxQmZWv4jnMRu2VWzJodsz4Bw
Content-Type: application/json

{
  "signupid": "admin001"
}

### 회원탈퇴 (아이디 길이 제한은 6이상 20이하이다.) (패스워드 길이제한은 8이상 20이하이다.)
DELETE http://localhost:8085/auth/delete
Content-Type: application/json

{
  "signupid": "uuuu999454554459",
  "password": "8888uuuu"
}

### 새로운 게시판 주제 생성 (관리자만 생성 가능, 이름 중복 불가능, 이름 길이 제한 : 2 이상 20 이하)
POST http://localhost:8085/topic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIwMTU3Mzg5LCJleHAiOjE3MjAxNjA5ODl9.tdQ7c89xL0q60Ucr8zdJXJDyiDv40xFkuaBoTYR9cUxzY5YW1GTOSVE7YjocCBTfxSCCVnUGnMlIQcyJXeWiPA
Content-Type: application/json

{
  "name": "감자탕"
}

### 기존의 게시판 주제 이름 수정 (관리자만 수정 가능, 이름 중복 불가능, 이름 길이 제한 : 2 이상 20 이하)
PUT http://localhost:8085/topic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIwMjI1NTg5LCJleHAiOjE3MjAyMjkxODl9.WycBRt0eGUnPkCntikIsUf9-0HACinimK9-Vt-IGwVCE3ECaIqi80G4XnDEr_FvkMj3iYkYJM2SDb3rx8aUu6Q
Content-Type: application/json

{
  "id": 6,
  "name": "감자탕22"
}

### 기존의 게시판 삭제 (관리자만 삭제 가능, 삭제하면 해당 게시판의 모든 게시글들도 삭제가 됩니다.)
DELETE http://localhost:8085/topic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIwMTYyMTc3LCJleHAiOjE3MjAxNjU3Nzd9.qxfDsBdNx9lOwDYPu0A8bAXsgTuob06NxOmo_k9h4eIhMrjQigfTPEiY8QA2t-k3JA97TqanmyvpOkVCc1Bv9g
Content-Type: application/json

{
  "id": 3
}

### 게시판 주제 조회 (이름 순으로 출력, keyword 항목을 추가하면 해당 키워드로 시작하는 주제들만 출력)
GET http://localhost:8085/topic/list?size=10&page=0