### 일반 사용자 회원가입 (아이디 중복 X, 아이디 길이 제한은 6이상 20이하이다.) (패스워드 길이제한은 8이상 20이하이다.) (닉네임 중복 X, 길이 제한은 2이상 12이하이다.)
POST http://localhost:8085/auth/signup-user
Content-Type: application/json

{
  "signupid": "user001",
  "password": "abcd001!?",
  "nickname": "안녕하세요"
}

### 관리자 회원가입 (아이디 중복 X, 아이디 길이 제한은 6이상 20이하이다.) (패스워드 길이제한은 8이상 20이하이다.) (닉네임 중복 X, 길이 제한은 2이상 12이하이다.)
POST http://localhost:8085/auth/signup-admin
Content-Type: application/json

{
  "signupid": "admin002",
  "password": "admin0101",
  "nickname": "ADMINADMIN2"
}

### 로그인 (아이디 길이 제한은 6이상 20이하이다.) (패스워드 길이제한은 8이상 20이하이다.)
POST http://localhost:8085/auth/signin
Content-Type: application/json

{
  "signupid": "user001",
  "password": "abcd001!?"
}

### 현재 로그인중인 사용자 정보 가져오기 (비밀번호 같은 민감한 정보는 반환되지 않습니다.)
GET http://localhost:8085/auth/signin-information
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDAxIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcyMDIzMDEyNywiZXhwIjoxNzIwMjMzNzI3fQ.FSE4yQhGRYIR8vDQJDDNlk1Q6ZZcc7yQUGuFAFaZGPlXpQg0mXfl7RV6MWH8E9Y0q9RlR9ogCpM3zOBf5xZIjA

### 사용자 고유 번호를 기반으로 다른 사용자 정보 가져오기 (로그인 필요 x)
GET http://localhost:8085/auth/information?id=3

### 사용자 정보 변경 (현재는 닉네임 변경을 위해 사용된다.) (닉네임 중복 X, 길이 제한은 2이상 12이하이다.)
PUT http://localhost:8085/auth/information
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDAxIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcyMDUwODI2MiwiZXhwIjoxNzIwNTExODYyfQ.8Go1FaelvG1sGn7TKcxtuOPjV9WOyuVEe98HpP4asXd6vVvk4JXG47BFl2Oj6WP5YO6lMsrKzDAhUu8NPs52tg
Content-Type: application/json

{
  "nickname": "튀김우동"
}

### 패스워드 변경 (패스워드 길이제한은 8이상 20이하이다.)
PUT http://localhost:8085/auth/password
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMDAxIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcyMDIzMDEyNywiZXhwIjoxNzIwMjMzNzI3fQ.FSE4yQhGRYIR8vDQJDDNlk1Q6ZZcc7yQUGuFAFaZGPlXpQg0mXfl7RV6MWH8E9Y0q9RlR9ogCpM3zOBf5xZIjA
Content-Type: application/json

{
  "password": "1234abcd"
}


### 유저 계정 잠금 (아이디 길이 제한은 6이상 20이하이다.) (관리자 계정으로 유저 계정을 잠그는 것만 가능)
PUT http://localhost:8085/auth/lock
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIwMjMwNzg4LCJleHAiOjE3MjAyMzQzODh9.mB1956jbbQTpJpHgkhIfN3relCnSy6zZworKnLULz5dEWe4M4cBH9gyPd2T2bwnZl01EWDwG5ZHgXtPRBRafSw
Content-Type: application/json

{
  "signupid": "user001"
}

### 유저 계정 잠금 해제 (아이디 길이 제한은 6이상 20이하이다.) (관리자 계정으로 유저 계정을 잠금 해제하는 것만 가능)
PUT http://localhost:8085/auth/unlock
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIwMjMwNzg4LCJleHAiOjE3MjAyMzQzODh9.mB1956jbbQTpJpHgkhIfN3relCnSy6zZworKnLULz5dEWe4M4cBH9gyPd2T2bwnZl01EWDwG5ZHgXtPRBRafSw
Content-Type: application/json

{
  "signupid": "user001"
}

### 회원탈퇴 (아이디 길이 제한은 6이상 20이하이다.) (패스워드 길이제한은 8이상 20이하이다.)
DELETE http://localhost:8085/auth/withdraw
Content-Type: application/json

{
  "signupid": "user001",
  "password": "abcd001!?"
}

### 새로운 게시판 주제 생성 (관리자만 생성 가능, 이름 중복 불가능, 이름 길이 제한 : 2 이상 20 이하)
POST http://localhost:8085/topic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIwMTU3Mzg5LCJleHAiOjE3MjAxNjA5ODl9.tdQ7c89xL0q60Ucr8zdJXJDyiDv40xFkuaBoTYR9cUxzY5YW1GTOSVE7YjocCBTfxSCCVnUGnMlIQcyJXeWiPA
Content-Type: application/json

{
  "name": "감자탕"
}

### 기존의 게시판 주제 이름 수정 (관리자만 수정 가능, 이름 중복 불가능, 이름 길이 제한 : 2 이상 20 이하)
PUT http://localhost:8085/topic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIwMjI1NTg5LCJleHAiOjE3MjAyMjkxODl9.WycBRt0eGUnPkCntikIsUf9-0HACinimK9-Vt-IGwVCE3ECaIqi80G4XnDEr_FvkMj3iYkYJM2SDb3rx8aUu6Q
Content-Type: application/json

{
  "id": 6,
  "name": "감자탕22"
}

### 기존의 게시판 삭제 (관리자만 삭제 가능, 삭제하면 해당 게시판의 모든 게시글들도 삭제가 됩니다.)
DELETE http://localhost:8085/topic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIwMTYyMTc3LCJleHAiOjE3MjAxNjU3Nzd9.qxfDsBdNx9lOwDYPu0A8bAXsgTuob06NxOmo_k9h4eIhMrjQigfTPEiY8QA2t-k3JA97TqanmyvpOkVCc1Bv9g
Content-Type: application/json

{
  "id": 3
}

### 게시판 주제 조회 (이름 순으로 출력, keyword 항목을 추가하면 해당 키워드로 시작하는 주제들만 출력)
GET http://localhost:8085/topic/list?size=10&page=0