### 새로운 게시판 주제 생성 (관리자만 생성 가능, 이름 중복 불가능, 이름 길이 제한 : 2 이상 20 이하)
POST http://localhost:8085/topic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIxMTEwMDAwLCJleHAiOjE3MjExMTM2MDB9.1OmWMdTBn1GbdvhXnxdhuG29uq7uIAPI_kTXS_DpWSRDtS-njwADK7vQ4T79HGXF8X0hLlCGnmJ1dXk4srYkpw
Content-Type: application/json

{
  "name": "음악"
}

### 기존의 게시판 주제 이름 수정 (관리자만 수정 가능, 이름 중복 불가능, 이름 길이 제한 : 2 이상 20 이하)
PUT http://localhost:8085/topic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIxMTA5OTg4LCJleHAiOjE3MjExMTM1ODh9.xe7xDYBmvOP51nHI1Cbk3Tl5cEp-lVROHW1YDG968VNBr5FbApDBy77FvX-Xola5ogRtLsRJir4axXSnvLY4CQ
Content-Type: application/json

{
  "id": 2,
  "name": "요리"
}

### 기존의 게시판 주제 삭제 (관리자만 삭제 가능, 삭제하면 해당 게시판의 모든 게시글들도 삭제가 됩니다.)
DELETE http://localhost:8085/topic
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjAwMSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzIxMTA5OTg4LCJleHAiOjE3MjExMTM1ODh9.xe7xDYBmvOP51nHI1Cbk3Tl5cEp-lVROHW1YDG968VNBr5FbApDBy77FvX-Xola5ogRtLsRJir4axXSnvLY4CQ
Content-Type: application/json

{
  "id": 4
}

### 게시판 주제 조회 (이름 순으로 출력, keyword 항목을 추가하면 해당 키워드로 시작하는 주제들만 출력)
GET http://localhost:8085/topic/list?size=10&page=0